### ISSUE TITLE
[BUG] Settings do not save when player disconnects

### ISSUE THREAD

**Issue by GodDirtman** [limbo56/PlayerSettings#46] opened 2022-12-09 23:05 UTC
**Describe the bug**

When players leave the server and join back, they don't have the effects from the settings they enabled. In settings' GUI the Enabled/Disabled state is being saved, but with no impact on the player.

**To Reproduce**

1. Turn on any setting in GUI, e.g. `speed`.
2. Leave the server and join again
3. When you join back, you do not have the effect applied, but the GUI displays the set state (Enabled/Disabled).

**Expected behavior**

Settings state should save.

**Server version**

`This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-298 (MC: 1.19.2)`

**Additional context**

Thanks for solving the previous issue I reported. Keep up the good work!

**Comment by limbo56** [comment] 2022-12-10 00:03
Hello @GodDirtman

Thanks again for helping iron out issues with the plugin. I've tried to reproduce this with the latest release, and it seems to behave fine on my end. Could you verify the configuration of your speed/jump settings has the new section called `triggers`? 

This new property is replacing the `executeOnJoin` property. It is a list of events/actions under which the setting should apply its effects. In the case of settings that use a potion effect (like speed and jump), you need to re-apply those potion effects when a player joins and respawns. Settings like the visibility, vanish and fly settings also need to apply their effects when a player joins.

Either way, here is an example of what your default speed and jump settings should look like:
```yaml
speed-setting:
  enabled: true
  default: 0
  max: 5
  triggers:
  - join # Applies the speed effect on join
  - respawn # Applies the speed effect on respawn

jump-setting:
  enabled: true
  default: 0
  max: 10
  triggers:
  - join # Applies the jump effect on join
  - respawn # Applies the jump effect on respawn
```

To avoid any further conflicts with the default settings, I recommend you generate a new `settings.yml` file and transfer over any changes. Sorry for the confusion, and I hope this helps.

**Comment by GodDirtman** [comment] 2022-12-10 16:08
For testing purposes, I ran the plugin on my standalone server, with no other plugins enabled. Just a pure Paper instance (so also no plugin data).

The plugin generated new files with default configurations and I began testing. Unfortunately, the issue still persists for me. I don't get the effects when rejoining the server, but GUI shows the previously set state correctly.  

I also double-checked the installed version of the plugin, and it is the latest one - 6.2.0.

**Comment by GodDirtman** [comment] 2022-12-10 17:18
Something told me to try redownloading the plugin, cause maybe I have some sort of half-corrupted file or something.

And well it worked. Now I just need to test it on my production server. 

I'm gonna close this if everything goes fine. Sorry for bothering you!

**Comment by limbo56** [comment] 2022-12-10 20:52
Hey, don't worry about asking questions. It doesn't bother me at all, and I'm more than glad to help with any issues you have with the plugin. Sorry about the confusion with the new changes. Others have also had trouble setting up the latest version. Please, feel free to open an issue here or contact me through the [plugin's discord server](https://discord.gg/6gkkJ6y) whenever you have a problem. I'm going to close this issue now, but you can comment here again if you are still having issues. Thanks a lot for reaching out, and I'm glad I could help you!

**Closed as not planned by limbo56** 2022-12-10 20:52 UTC
Labels: bug, enhancement
